"""Drop overall anaysis from task summaries table

Revision ID: 3c2ca23d9227
Revises: 80e07be09f0e
Create Date: 2025-09-15 12:19:56.408193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c2ca23d9227"
down_revision: Union[str, Sequence[str], None] = "80e07be09f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_summaries", "overall_recommendations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_summaries",
        sa.Column(
            "overall_recommendations",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
