"""Initial migration

Revision ID: ac105fcf9417
Revises:
Create Date: 2025-09-12 11:02:38.203853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ac105fcf9417"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "repo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column(
            "github_token", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "celery_task_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "requested_by", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_tasks_celery_task_id"),
        "analysis_tasks",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_tasks_created_at"),
        "analysis_tasks",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_tasks_pr_number"),
        "analysis_tasks",
        ["pr_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_tasks_repo_url"), "analysis_tasks", ["repo_url"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_tasks_status"), "analysis_tasks", ["status"], unique=False
    )
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "file_name", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("issues", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("suggestions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("analysis_duration", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["analysis_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_results_file_name"),
        "analysis_results",
        ["file_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_task_id"),
        "analysis_results",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "analysis_summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("total_issues", sa.Integer(), nullable=False),
        sa.Column("critical_issues", sa.Integer(), nullable=False),
        sa.Column("high_issues", sa.Integer(), nullable=False),
        sa.Column("medium_issues", sa.Integer(), nullable=False),
        sa.Column("low_issues", sa.Integer(), nullable=False),
        sa.Column("style_issues", sa.Integer(), nullable=False),
        sa.Column("bug_issues", sa.Integer(), nullable=False),
        sa.Column("performance_issues", sa.Integer(), nullable=False),
        sa.Column("security_issues", sa.Integer(), nullable=False),
        sa.Column("maintainability_issues", sa.Integer(), nullable=False),
        sa.Column("best_practice_issues", sa.Integer(), nullable=False),
        sa.Column("code_quality_score", sa.Float(), nullable=False),
        sa.Column("maintainability_score", sa.Float(), nullable=False),
        sa.Column("overall_recommendations", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["analysis_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_summaries_task_id"),
        "analysis_summaries",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analysis_summaries_task_id"), table_name="analysis_summaries"
    )
    op.drop_table("analysis_summaries")
    op.drop_index(op.f("ix_analysis_results_task_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_file_name"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_analysis_tasks_status"), table_name="analysis_tasks")
    op.drop_index(op.f("ix_analysis_tasks_repo_url"), table_name="analysis_tasks")
    op.drop_index(op.f("ix_analysis_tasks_pr_number"), table_name="analysis_tasks")
    op.drop_index(op.f("ix_analysis_tasks_created_at"), table_name="analysis_tasks")
    op.drop_index(op.f("ix_analysis_tasks_celery_task_id"), table_name="analysis_tasks")
    op.drop_table("analysis_tasks")
    # ### end Alembic commands ###
