"""Drop suggestions columns from file issues since issues array already contain a suggestion for every issue

Revision ID: e60ea05371b9
Revises: 3c2ca23d9227
Create Date: 2025-09-15 12:33:04.813588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e60ea05371b9"
down_revision: Union[str, Sequence[str], None] = "3c2ca23d9227"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_results", "suggestions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results",
        sa.Column(
            "suggestions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
